name: krish
description: "A Flutter app for farmers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Networking & utilities
  http: ^1.5.0
  url_launcher: ^6.3.2
  image_picker: ^1.0.7
  weather_icons: ^3.0.0

  # Google Sign-In for Supabase
  google_sign_in: ^6.2.1

  # Local storage
  shared_preferences: ^2.3.3

  # Localization
  intl: ^0.20.2

  # Supabase
  supabase_flutter: ^2.5.0

  # Charts
  fl_chart: ^0.69.2

  # Voice + Speech
#  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0

  # Environment variables
  flutter_dotenv: ^6.0.0

  # Gemini AI
  google_generative_ai: ^0.4.3

  # Location
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/.env
    - assets/images/
    - assets/images/google.png

    













# name: krishinoor
# description: "A Flutter app for farmers."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: '>=3.4.3 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#   flutter_localizations:
#     sdk: flutter

#   # UI
#   cupertino_icons: ^1.0.8

#   # Networking & utilities
#   http: ^1.5.0
#   url_launcher: ^6.3.2
#   image_picker: ^1.0.7
#   weather_icons: ^3.0.0

#   # Firebase
#   firebase_core: ^4.1.0
#   cloud_firestore: ^6.0.1
#   firebase_storage: ^13.0.1

#   # Local storage
#   shared_preferences: ^2.3.3

#   # Localization
#   intl: ^0.20.2

#   # Supabase
#   supabase_flutter: ^2.5.0

#   fl_chart: ^0.69.2

#   flutter_tts: ^4.2.3
#   speech_to_text: ^7.3.0
#   flutter_dotenv: ^6.0.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^6.0.0
#   flutter_launcher_icons: ^0.14.4

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/logo.png"
#   adaptive_icon_background: "#ffffff"
#   adaptive_icon_foreground: "assets/images/logo.png"

# flutter:
#   uses-material-design: true
#   generate: true

#   assets:
#     - .env
#     - assets/images/


